<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Email Confirmation</title>
</head>
<body>
<h1 style="color: green">Новый пароль</h1>
<h2>Добрый день, ${name}!</h2>
<p>Обращаем Ваше внимание, что Ваш пароль был успешно изменён.</p>
<p>Новый пароль для DiaHelper:  <b> ${password}</b></p>
<p></p>
<p>Желаем Вам хорошено дня!</p>
<p>С уважением команда DiaHelper</p>
</body>
</html>